name: MLflow Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-mlflow:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Load the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ Install requirements
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[all]
          pip install mlflow

      # 4️⃣ Run the pipeline (DVC + MLflow)
      - name: Run DVC pipeline
        run: |
          dvc pull -v
          dvc repro -v

      # 5️⃣ Save MLflow results as artifact
      - name: Upload MLflow runs
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-runs
          path: mlruns/
